#!/bin/sh /etc/rc.common
# Copyright (C) 2022 Hak5.org

USE_PROCD=1
START=99

start_service() {
    procd_open_instance
    procd_set_param respawn 0 ${respawn_timeout:-5} ${respawn_retry:-5}
    procd_set_param command /usr/sbin/cc-client /etc/device.config
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

stop_service() {
    rm /tmp/cc-client.lock
}

