src/gz shark_jack_display_core https://downloads.openwrt.org/releases/23.05.5/targets/ramips/mt76x8/packages
src/gz shark_jack_display_base https://downloads.openwrt.org/releases/23.05.5/packages/mipsel_24kc/base
src/gz shark_jack_display_hak5 https://downloads.openwrt.org/releases/23.05.5/packages/mipsel_24kc/hak5
src/gz shark_jack_display_luci https://downloads.openwrt.org/releases/23.05.5/packages/mipsel_24kc/luci
src/gz shark_jack_display_packages https://downloads.openwrt.org/releases/23.05.5/packages/mipsel_24kc/packages
src/gz shark_jack_display_routing https://downloads.openwrt.org/releases/23.05.5/packages/mipsel_24kc/routing
src/gz shark_jack_display_telephony https://downloads.openwrt.org/releases/23.05.5/packages/mipsel_24kc/telephony
