#!/bin/bash

# This is a collection of helpers for shark framework and
# accompanying scripts

source /usr/lib/shark_text_helpers
source /usr/lib/shark_ip_helpers

SSH_CONTEXT=false
if [[ -n "$SSH_CONNECTION" ]]; then
  SSH_CONTEXT=true
fi
export SSH_CONTEXT

config_theme="$(cat /tmp/theme)"

update_theme() {
  config_theme="$1"
}

screen_write() {
  echo -en "$@" > /dev/tty0
  if [ "$SSH_CONTEXT" = true ]; then
    echo -en "$@" > /dev/tty
  fi

  touch /tmp/interaction
  # echo "write" >> /tmp/debug.log
}

disable_cursor_blink() {
  echo -en "\033[?25l" > /dev/tty0
}

disable_text_wrap() {
  echo -en "\033[?7l" > /dev/tty0
}

enable_text_wrap() {
  echo -en '\033[?7h' > /dev/tty0
}

clear_screen() {
  echo -en "\033[2J\033[H" > /dev/tty0

  # echo "clear" >> /tmp/debug.log
  if [ $SSH_CONTEXT = "true" ]; then
    echo -en "\033[2J\033[H" > /dev/tty
  fi
}

use_configured_theme() {
  if [ "$config_theme" = "LIGHT" ]; then
    echo -en "\033[?5h" > /dev/tty0
  else
    echo -en "\033[?5l" > /dev/tty0
  fi
}

full_screen_invert() {
  if [ "$config_theme" = "LIGHT" ]; then
    echo -en "\033[?5l" > /dev/tty0
  else
    echo -en "\033[?5h" > /dev/tty0
  fi
}

full_screen_invert_reset() {
  if [ "$config_theme" = "LIGHT" ]; then
    echo -en "\033[?5h" > /dev/tty0
  else
    echo -en "\033[?5l" > /dev/tty0
  fi
}
